name: shamfm_ios
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.18.12

  http: ^1.1.0
  just_audio: ^0.9.36
  provider: ^6.1.1
  shimmer: ^3.0.0
  page_transition: ^2.1.0
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_neumorphic:  
    git:
      url: https://github.com/Idean/Flutter-Neumorphic.git
      ref: 07f44e0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Icons/
    - assets/horoscopes/

flutter_launcher_icons:
  image_path: "assets/Shamfm.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"