name: shamfm_ios
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.18.12
  flutter_neumorphic: ^3.2.0
  http: ^1.1.0
  just_audio: ^0.9.36
  provider: ^6.1.1
  shimmer: ^3.0.0
  page_transition: ^2.1.0
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Icons/
    - assets/horoscopes/
